import { NextRequest, NextResponse } from "next/server";
import { isAuthenticated } from "@/lib/auth";
import axios from 'axios';

async function uploadToPinata(imageData: string, fid: number) {
  const pinataApiKey = process.env.PINATA_API_KEY!;
  const pinataSecretApiKey = process.env.PINATA_API_SECRET!;

  // Convert base64 to a Blob
  const imageBuffer = Buffer.from(imageData.split(",")[1], "base64");
  const imageBlob = new Blob([imageBuffer], { type: "image/png" });

  // Create a FormData object and append the file and options
  const form = new FormData();
  form.append("file", imageBlob, `ReligiousWarplet_${fid}_${Date.now()}.png`);

  const pinataMetadata = JSON.stringify({
    name: `ReligiousWarplet Image for FID ${fid}`,
  });
  form.append("pinataMetadata", pinataMetadata);

  const pinataOptions = JSON.stringify({
    cidVersion: 1,
  });
  form.append("pinataOptions", pinataOptions);

  // Pin the file to IPFS using Axios
  const pinFileResponse = await axios.post("https://api.pinata.cloud/pinning/pinFileToIPFS", form, {
    headers: {
      // Axios will automatically set the Content-Type with the correct boundary
      'pinata_api_key': pinataApiKey,
      'pinata_secret_api_key': pinataSecretApiKey,
    },
  });

  const { IpfsHash: imageIpfsHash } = pinFileResponse.data;
  const imageUrl = `ipfs://${imageIpfsHash}`;

  // Create and pin the metadata JSON
  const metadata = {
    name: "Religious Warplet",
    description: "A unique piece of religious art generated for the holder.",
    image: imageUrl,
    attributes: [{ trait_type: "Generated By", value: `FID: ${fid}` }],
  };
  
  const pinMetadataResponse = await axios.post("https://api.pinata.cloud/pinning/pinJSONToIPFS", {
      pinataContent: metadata,
      pinataMetadata: { name: `ReligiousWarplet_Metadata_${fid}_${Date.now()}.json` },
      pinataOptions: { cidVersion: 1 }
  }, {
    headers: {
      'Content-Type': 'application/json',
      'pinata_api_key': pinataApiKey,
      'pinata_secret_api_key': pinataSecretApiKey,
    }
  });

  const { IpfsHash: metadataIpfsHash } = pinMetadataResponse.data;
  return `ipfs://${metadataIpfsHash}`;
}

export async function POST(request: NextRequest) {
  if (!process.env.PINATA_API_KEY || !process.env.PINATA_API_SECRET) {
    console.error("Pinata API keys are not configured.");
    return NextResponse.json({ message: "Server configuration error: Missing Pinata credentials." }, { status: 500 });
  }

  const fid = await isAuthenticated(request);
  if (fid instanceof NextResponse) {
    return fid;
  }

  const { imageData } = await request.json();
  if (!imageData) {
    return NextResponse.json({ message: "Missing imageData" }, { status: 400 });
  }

  try {
    console.log("Starting IPFS upload process with Axios and native FormData...");
    const tokenUri = await uploadToPinata(imageData, fid);
    console.log("Successfully uploaded to IPFS. Token URI:", tokenUri);
    return NextResponse.json({ tokenUri }, { status: 200 });
  } catch (error) {
    console.error("Error during IPFS upload process:", error);
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
    return NextResponse.json({ message: `Error uploading to IPFS: ${errorMessage}` }, { status: 500 });
  }
}